# Generated by Django 3.1.4 on 2020-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20201208_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='image',
            field=models.ImageField(height_field=571, upload_to='Site/images', width_field=692),
        ),
    ]
