# Generated by Django 3.1.4 on 2020-12-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20201209_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='image',
            field=models.ImageField(max_length=255, upload_to='Site/images'),
        ),
    ]
