# Generated by Django 3.1.4 on 2020-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_auto_20201209_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Site/images'),
        ),
    ]
