# Generated by Django 3.1.4 on 2020-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20201209_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='GitHub link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliopost',
            name='Playstore Link',
            field=models.CharField(max_length=200),
        ),
    ]
