# Generated by Django 3.1.4 on 2020-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_auto_20201211_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopost',
            name='GitHub link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfoliopost',
            name='Playstore Link',
            field=models.CharField(max_length=200),
        ),
    ]
