# Generated by Django 3.1.4 on 2020-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_auto_20201211_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopost',
            name='GitHub link',
        ),
        migrations.RemoveField(
            model_name='portfoliopost',
            name='Playstore Link',
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='gitHubLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='playStoreLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
