# Generated by Django 3.1.4 on 2020-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20201211_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopost',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
